name: Android CI Release

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  go-build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0

    steps:

      - name: Checkout codebase
        uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Show workflow information
        run: |
          export _NAME=$GOOS-$GOARCH$GOARM$GOMIPS.${GITHUB_SHA::6}
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.0'
          check-latest: true

      # Set up JDK
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          link-to-sdk: true

      - name: Install Gomobile and Build native parts
        run: |
          for d in $ANDROID_NDK_HOME/../26*; do
            ANDROID_NDK_HOME=$d
          done
          cd app/libs
          go mod tidy
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest
          go get golang.org/x/mobile/cmd/gobind
          go get golang.org/x/mobile/cmd/gomobile
          go get golang.org/x/mobile
          gomobile init
          gomobile bind -ldflags '-s -w' -o tun2socks.aar -androidapi 21 -target android .
          cd ../..
        env:
          GOPROXY: https://proxy.golang.org,direct
          GO111MODULE: "on"

        uses: softprops/action-gh-release@v1
        with:
          files: app-release-signed.apk
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  android-build-and-release:
    needs: go-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > my-release-key.keystore
          ./gradlew signReleaseBundle \
            --no-daemon \
            -Pandroid.injected.signing.store.file=my-release-key.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEY_STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}

      - name: Upload Signed APK to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Signed APK
          path: app/build/outputs/apk/release/app-release.apk

      - name: Release APK
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
